# name: CD Pipeline

# on:
#   push:
#     branches: ['main']
#   workflow_run:
#     workflows: ['CI Pipeline']
#     types:
#       - completed

# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Pull Docker image
#         run: sudo docker pull cherkaoui97/pharmadirect:latest

#       - name: Ensure Old Docker Container is Stopped and Removed
#         run: |
#           sudo docker stop pharmadirect-container || true
#           sudo docker rm -f pharmadirect-container || true

#       - name: Check if port 3000 is in use
#         run: |
#           if sudo ss -tuln | grep -q ':3000'; then
#             echo "Port 3000 is in use. Stopping conflicting container or process."
#             sudo fuser -k 3000/tcp || true
#           fi

#       - name: Create .env file
#         run: |
#           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
#           echo "PORT=${{ secrets.PORT }}" >> .env
#           echo "jwtConstants=${{ secrets.jwtConstants }}" >> .env
#           echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
#           echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env
#           echo "NODE_ENV=production" >> .env

#       - name: Run Docker Container with .env
#         run: sudo docker run -d -p ${{ secrets.PORT }}:3000 --env-file .env --name pharmadirect-container cherkaoui97/pharmadirect

